FROM python:3.10-slim AS builder

RUN mkdir /py_api

WORKDIR /py_api

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY requirements.txt /py_api/

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.10-slim

RUN useradd -m -r py_api && \
        mkdir /py_api && \
        chown -R py_api /py_api

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin

WORKDIR /py_api

COPY --chown=py_api:py_api . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH=$PATH:/home/py_api/.local/bin

USER py_api

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "py_api.wsgi:application"]