# Generated by Django 5.2.4 on 2025-07-14 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_description_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Only alphanumeric characters (0-9, A-Z, a-z), hyphens (-) and/or underscores (_) allowed in username', regex='^[\\w.~-]*$')]),
        ),
    ]
