# Generated by Django 5.2.4 on 2025-07-19 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_profile_author_profile_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bluesky',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_at_proto_handle', message='Invalid ATProtocol handle, please refer to specifications for valid values. https://atproto.com/specs/handle.', regex='^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$')]),
        ),
    ]
