# Generated by Django 5.2.4 on 2025-07-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0011_usersubscription_user_subscribers_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_token_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['confirmation_token'], include=('confirmation_token_sent_at', 'confirmed', 'confirmed_at', 'id'), name='users_confirmation_token_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['confirmed', 'id'], include=('email', 'username'), name='confirmed_users_idx'),
        ),
    ]
