# Generated by Django 5.2.4 on 2025-07-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_user_options_user_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='confirmation_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='confirmation_token_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['confirmation_token'], include=('confirmation_token_sent_at', 'confirmed', 'confirmed_at', 'id'), name='subscription_confirmation_idx'),
        ),
    ]
