# Generated by Django 5.2.4 on 2025-07-26 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_subscription_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', False), ('type__exact', 'comment')), ('comment__isnull', True), _connector='OR'), name='ensure_notification_type_comment_has_comment'),
        ),
    ]
