# Generated by Django 5.2.4 on 2025-07-27 00:06

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_notification_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)])),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing')])),
                ('title', models.CharField(max_length=70)),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_projects'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status__exact', 'ongoing')), ('finished_at__isnull', False), _connector='OR'), name='ensure_finished_at_for_completed_projects')],
            },
        ),
    ]
