from django.urls import path

from . import views as blog_views

app_name = "blog"

urlpatterns = [
    path(
        "user/profile/<username>",
        blog_views.ProfileView.as_view(),
        name="profile_detail_path",
    ),
    path("user/register", blog_views.RegisterView.as_view(), name="register_path"),
    path(
        "user/confirmation/<signed_confirmation_token>",
        blog_views.ConfirmationView.as_view(),
        name="confirmation_path",
    ),
    path(
        "user/token",
        blog_views.BlogTokenObtainPairView.as_view(),
        name="login_path",
    ),
    path(
        "subscribe/<username>",
        blog_views.SubscriptionCreateAPIView.as_view(),
        name="subscribe_path",
    ),
    path(
        "subscription/confirmation/<signed_confirmation_token>",
        blog_views.SubscriptionConfirmationUpdateAPIView.as_view(),
        name="subscription_confirmation_path",
    ),
    path("posts", blog_views.PostListCreateAPIView.as_view(), name="posts_path"),
    path(
        "posts/bookmark",
        blog_views.BookmarkCreateAPIView.as_view(),
        name="create_or_delete_bookmark_path",
    ),
    path(
        "posts/comment",
        blog_views.CommentCreateAPIView.as_view(),
        name="create_comment_path",
    ),
    path(
        "posts/like",
        blog_views.PostLikeCreateAPIView.as_view(),
        name="create_or_delete_like_path",
    ),
    path(
        "posts/<username>",
        blog_views.PostListByUserAPIView.as_view(),
        name="posts_by_user_path",
    ),
    path(
        "posts/<username>/<slug>",
        blog_views.PostRetrieveAPIView.as_view(),
        name="post_detail_path",
    ),
    path(
        "projects",
        blog_views.ProjectListAPIView.as_view(),
        name="projects_path",
    ),
    path(
        "projects/<username>",
        blog_views.ProjectListByUsernameAPIView.as_view(),
        name="projects_by_username_path",
    ),
    path(
        "projects/<username>/<slug>",
        blog_views.ProjectRetrieveAPIView.as_view(),
        name="project_detail_path",
    ),
    path(
        "dashboard/posts/<post_id>",
        blog_views.DashboardPostRetrieveUpdateDestroyAPIView.as_view(),
        name="post_update_path",
    ),
    path(
        "categories",
        blog_views.CategoryListCreateAPIView.as_view(),
        name="categories_path",
    ),
    path(
        "categories/<username>",
        blog_views.CategoryListByUserAPIView.as_view(),
        name="categories_by_user_path",
    ),
    path(
        "categories/<username>/<slug>",
        blog_views.CategoryRetrieveAPIView.as_view(),
        name="category_detail_path",
    ),
    path(
        "categories/<username>/<slug>/posts",
        blog_views.CategoryPostsListAPIView.as_view(),
        name="category_posts_path",
    ),
    path(
        "dashboard/bookmarks",
        blog_views.DashboardBookmarkListsAPIView.as_view(),
        name="dashboard_bookmarks_path",
    ),
    path(
        "dashboard/categories",
        blog_views.DashboardCategoryListsAPIView.as_view(),
        name="dashboard_categories_path",
    ),
    path(
        "dashboard/categories/<slug>",
        blog_views.DashboardCategoriesRetrieveUpdateDestroyAPIView.as_view(),
        name="dashboard_category_detail_path",
    ),
    path(
        "dashboard/comments",
        blog_views.DashboardCommentListsAPIView.as_view(),
        name="dashboard_comments_path",
    ),
    path(
        "dashboard/comments/<id>",
        blog_views.DashboardCommentsRetrieveDestroyAPIView.as_view(),
        name="dashboard_retrieve_destroy_comment_path",
    ),
    path(
        "dashboard/stats",
        blog_views.AuthorStatsAPIView.as_view(),
        name="dashboard_stats_path",
    ),
    path(
        "dashboard/posts",
        blog_views.DashboardPostListsAPIView.as_view(),
        name="dashboard_posts_path",
    ),
    path(
        "dashboard/notifications/<notification_id>",
        blog_views.NotificationUpdateAPIView.as_view(),
        name="dashboard_notification_detail_path",
    ),
    path(
        "dashboard/notifications",
        blog_views.NotificationListAPIView.as_view(),
        name="dashboard_notifications_path",
    ),
    path(
        "dashboard/profile",
        blog_views.DashboardProfileRetrieveUpdateAPIView.as_view(),
        name="dashboard_profile_path",
    ),
    path(
        "dashboard/projects",
        blog_views.DashboardProjectListCreateAPIView.as_view(),
        name="dashboard_projects_path",
    ),
    path(
        "dashboard/projects/<slug>",
        blog_views.DashboardProjectRetrieveUpdateDestroyAPIView.as_view(),
        name="dashboard_project_detail_path",
    ),
    path(
        "dashboard/subscriptions",
        blog_views.DashboardSubscriptionListsAPIView.as_view(),
        name="dashboard_subscriptions_path",
    ),
    path(
        "dashboard/user_subscriptions",
        blog_views.DashboardUserSubscriptionListsAPIView.as_view(),
        name="dashboard_user_subscriptions_path",
    ),
    path(
        "dashboard/subscribe/<username>",
        blog_views.DashboardUserSubscriptionCreateAPIView.as_view(),
        name="dashboard_user_subscriptions_subscribe_path",
    ),
    path(
        "dashboard/user_subscriptions/<id>",
        blog_views.DashboardUserSubscriptionRetrieveUpdateAPIView.as_view(),
        name="dashboard_user_subscriptions_detail_path",
    ),
]
